[package]
name = "ics10-grandpa"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]


[features]
default = ["std"]
std = [
    "ibc/std",
    "ibc-proto/std",
    "grandpa-client/std",
    "grandpa-client-primitives/std",
    "light-client-common/std",
]

[dependencies]
# ibc deps
ibc = { git = "https://github.com/ComposableFi/ibc-rs", rev = "d4b034e6768a3553a7d0ca9e2e3d532e3cea5f29", default-features = false }
ibc-proto = { git = "https://github.com/ComposableFi/ibc-rs", rev = "d4b034e6768a3553a7d0ca9e2e3d532e3cea5f29", default-features = false }
# local deps
grandpa-client = { package = "grandpa-light-client", path = "../../algorithms/grandpa",  default-features = false }
grandpa-client-primitives = { package = "grandpa-light-client-primitives", path = "../../algorithms/grandpa/primitives", default-features = false }
light-client-common = { path = "../common", default-features = false }
