[workspace]
resolver = "2"
members = [
    "algorithms/beefy/prover",
    "algorithms/beefy/primitives",
    "algorithms/beefy",
    "algorithms/grandpa",
    "algorithms/grandpa/primitives",
    "algorithms/grandpa/prover",
    "light-clients/ics11_beefy",
    "light-clients/ics13_near",
]
