type = 'parachain'
name = 'rococo_local'
para_id = 2000
parachain_rpc_url = 'ws://127.0.0.1:9188'
relay_chain_rpc_url = 'ws://127.0.0.1:9944'
connection_id = 'connection-0'
beefy_activation_block = 0
commitment_prefix = '0x6962632f' # ibc/
private_key = '//Alice'
ss58_version = 49
channel_whitelist = []
finality_protocol = 'Grandpa'
key_type = 'sr25519'
client_id = "08-wasm-0"
counterparty_wasm_code_id = "1322d57aa7b6a44bb9306cd58a86277d0d90bad2bbe453ffe3026d1ba48ae9fd"
