type = 'parachain'
name = 'rococo_local'
para_id = 2000
parachain_rpc_url = 'ws://127.0.0.1:9188'
relay_chain_rpc_url = 'ws://127.0.0.1:9944'
connection_id = 'connection-0'
beefy_activation_block = 0
commitment_prefix = '0x6962632f' # ibc/
private_key = '//Alice'
ss58_version = 49
channel_whitelist = []
finality_protocol = 'Grandpa'
key_type = 'sr25519'
client_id = "08-wasm-0"
counterparty_wasm_code_id = "6b1025f8e590cd41071e75171c5c67b632ef8466ed7fc23251b6f1fbe1295a22"