type = 'parachain'
name = 'rococo-local'
para_id = 2000
parachain_rpc_url = 'ws://127.0.0.1:9188'
relay_chain_rpc_url = 'ws://127.0.0.1:9944'
connection_id = 'connection-0'
beefy_activation_block = 0
commitment_prefix = '0x6962632f'
private_key = '//Alice'
ss58_version = 49
channel_whitelist = []
finality_protocol = 'Grandpa'
key_type = 'sr25519'
client_id = "07-tendermint-0"
