version: "0.5"

environment:
  - "GLOBAL_ENV_VAR=1"
log_location: /tmp/logfile.log
log_level: debug

processes:
  network-a:
    command: "zombienet spawn ./config-network-a.json --provider native"
    availability:
      restart: "never"
    readiness_probe:
      exec:
        command: |
          if [[ $( curl http://127.0.0.1:39988/metrics | grep --extended-regexp 'substrate_block_height{status="finalized",chain="[a-zA-Z-]+"}' | tr -s " " | cut --delimiter " " --fields=2 ) > 1 ]]; then
            echo "Network A is ready"
          else
            exit 1
          fi
      failure_threshold: 32
      initial_delay_seconds: 32
      period_seconds: 8
      success_threshold: 1
      timeout_seconds: 2

  network-b:
    command: "zombienet spawn ./config-network-b.json --provider native"
    availability:
      restart: "never"
    readiness_probe:
      exec:
        command: |
          if [[ $( curl http://127.0.0.1:39998/metrics | grep --extended-regexp 'substrate_block_height{status="finalized",chain="[a-zA-Z-]+"}' | tr -s " " | cut --delimiter " " --fields=2 ) > 1 ]]; then
            echo "Network B is ready"
          else
            exit 1
          fi
      failure_threshold: 32
      initial_delay_seconds: 32
      period_seconds: 8
      success_threshold: 1
      timeout_seconds: 2      