version: "0.5"

environment:
  - "GLOBAL_ENV_VAR=1"
log_location: /tmp/logfile.log
log_level: debug

processes:
  network-a:
    command: "zombienet spawn ./config-network-a.json --provider native"
    availability:
      restart: "never"
    readiness_probe:
      exec:
        command: |
                curl http://127.0.0.1:39944/metrics | grep polkadot_parachain_chain_api_block_headers_count | tr -s " " | cut --delimiter " " --fields=2 | tee /tmp/zombie-example-a/polkadot_parachain_chain_api_block_headers_count
                exit $(( $(cat /tmp/zombie-example-a/polkadot_parachain_chain_api_block_headers_count) > 4 ? 0 : 1 ))
      failure_threshold: 32
      initial_delay_seconds: 16
      period_seconds: 8
      success_threshold: 1
      timeout_seconds: 2

  network-b:
    command: "zombienet spawn ./config-network-b.json --provider native"
    availability:
      restart: "never"
    readiness_probe:
      exec:
        command: |
                curl http://127.0.0.1:39954/metrics | grep polkadot_parachain_chain_api_block_headers_count | tr -s " " | cut --delimiter " " --fields=2 | tee /tmp/zombie-example-a/polkadot_parachain_chain_api_block_headers_count
                exit $(( $(cat /tmp/zombie-example-a/polkadot_parachain_chain_api_block_headers_count) > 4 ? 0 : 1 ))
      failure_threshold: 32
      initial_delay_seconds: 16
      period_seconds: 8
      success_threshold: 1
      timeout_seconds: 2      