[package]
name = "subxt-generated"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { workspace = true }
parity-scale-codec = { workspace = true, default-features = false, features = [
    "derive",
    "max-encoded-len",
] }
