[package]
name = "grandpa-light-client-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[dependencies]
# crates.io
anyhow = { version = "1.0.64", default-features = false }
hash-db = { version = "0.16.0", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }
sp-storage = { version = "6.0.0", default-features = false }
finality-grandpa = { workspace = true, features = ["derive-codec"], default-features = false }
parity-scale-codec = { workspace = true }
log = { workspace = true }
# substrate
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-runtime = { workspace = true }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43", default-features = false }
frame-support = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-std = { workspace = true }
sp-trie = { workspace = true }

light-client-common = { path = "../../../light-clients/common", default-features = false }

[features]
default = ["std"]
std = [
	"anyhow/std",
	"hash-db/std",
	"sp-storage/std",
	"finality-grandpa/std",
	"parity-scale-codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"frame-support/std",
	"sp-consensus-grandpa/std",
	"sp-std/std",
	"sp-trie/std",
	"light-client-common/std",
	"log/std"
]
