[package]
name = "icsxx-ethereum"
version = "0.1.0"
edition = "2021"
authors = ["Vladislav Markushin <negigic@gmail.com>"]

[build-dependencies]
prost-build = "0.11.1"

[dependencies]
# ibc deps
ibc = { path = "../../ibc/modules", default-features = false }
ibc-proto = { path = "../../ibc/proto", default-features = false }

# local deps
sync-committee-verifier = { git = "https://github.com/polytope-labs/sync-committee-rs.git", rev = "4e45ae9797198a617abfcbff098253cedc8a1f2e", default-features = false }
sync-committee-primitives = { git = "https://github.com/polytope-labs/sync-committee-rs.git", rev = "4e45ae9797198a617abfcbff098253cedc8a1f2e", default-features = false }
light-client-common = { path = "../common", default-features = false }
#ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", rev = "48335b5c8074d63553ee4681993e294eba947f88", default-features = false }
#ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", rev = "96f9a89ccc56ab2abb4c3a83eaedb415034ada49", default-features = false }
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", branch = "main", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main" , default-features = false }

# crates.io
prost = { version = "0.11", default-features = false }
prost-types = { version = "0.11", default-features = false }
anyhow = { version = "1.0.65", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }
serde = { version = "1.0.144", default-features = false, features = ["derive"] }

# substrate deps

tendermint = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }

[dev-dependencies]
hex = "0.4.3"
log = "0.4"
futures = "0.3.24"
env_logger = "0.9.0"
serde = { version = "1.0.144", features = ["derive"] }
ibc = { path = "../../ibc/modules", features = ["mocks"] }
ibc-derive = { path = "../../ibc/derive" }
tokio = { version = "1.21.1", features = ["macros"] }
json = { package = "serde_json", version = "1.0.85" }
jsonrpsee-ws-client = "0.16.2"
actix-rt = "2.3.0"
sync-committee-primitives = { git = "https://github.com/polytope-labs/sync-committee-rs.git", rev = "4e45ae9797198a617abfcbff098253cedc8a1f2e", features = ["testing"] }
sync-committee-verifier = { git = "https://github.com/polytope-labs/sync-committee-rs.git", rev = "4e45ae9797198a617abfcbff098253cedc8a1f2e", features = ["testing"] }
sync-committee-prover = { git = "https://github.com/polytope-labs/sync-committee-rs.git", rev = "4e45ae9797198a617abfcbff098253cedc8a1f2e" }

[features]
#default = ["std"]
default = ["std"]
std = [
    "ibc/std",
    "ibc-proto/std",
    "light-client-common/std",
    "prost/std",
    "prost-types/std",
    "anyhow/std",
    "serde/std",
    "sync-committee-verifier/std",
    "sync-committee-primitives/std",
    "ethereum-consensus/std",
    "ssz-rs/std",
    "tendermint/std",
]
