[package]
name = "icsxx-ethereum"
version = "0.1.0"
edition = "2021"
authors = ["Vladislav Markushin <negigic@gmail.com>"]

[build-dependencies]
prost-build = "0.11.1"

[dependencies]
# ibc deps
ibc = { path = "../../ibc/modules", default-features = false }
ibc-proto = { path = "../../ibc/proto", default-features = false }

# local deps
sync-committee-verifier = { git = "https://github.com/polytope-labs/hyperbridge.git", rev = "7adb936a6fdf4a9cc418259bf0cec35a31ce35d8", default-features = false }
sync-committee-primitives = { git = "https://github.com/polytope-labs/hyperbridge.git", rev = "7adb936a6fdf4a9cc418259bf0cec35a31ce35d8", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main" , default-features = false }
primitive-types = { version = "0.12.0", default-features = false, features = ["serde_no_std"]}

# crates.io
prost = { version = "0.11", default-features = false }
prost-types = { version = "0.11", default-features = false }
anyhow = { version = "1.0.65", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }
serde = { version = "1.0.144", default-features = false, features = ["derive"] }

# substrate deps

tendermint = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }
rs_merkle = { version = "1.4.1", default-features = false }
hash-db = { version = "0.16.0", default-features = false }
trie-db = { version = "0.28.0", default-features = false }
rlp = { version = "0.5.2", default-features = false }
hex-literal = { version = "0.4.1", default-features = false }
hash256-std-hasher = { version = "0.15.2", default-features = false }
ethabi = { version = "18.0.0", default-features = false }
alloy-sol-macro = { version = "0.4.2", default-features = false, features = ["json"] }
alloy-sol-types = { version = "0.4.2", default-features = false }
tiny-keccak = { version = "2.0.2", default-features = false, features = ["keccak"] }
log = "0.4"
deflate = { version = "1.0.0", default-features = false }
hex = "0.4.3"
parity-scale-codec = { version = "1.3.4", default-features = false }
compress = { path = "../../utils/compress", default-features = false }

[dev-dependencies]
futures = "0.3.24"
env_logger = "0.9.0"
serde = { version = "1.0.144", features = ["derive"] }
ibc = { path = "../../ibc/modules", features = ["mocks"] }
ibc-derive = { path = "../../ibc/derive" }
tokio = { version = "1.21.1", features = ["macros"] }
json = { package = "serde_json", version = "1.0.85" }
jsonrpsee-ws-client = "0.16.2"
actix-rt = "2.3.0"
sync-committee-primitives = { git = "https://github.com/polytope-labs/hyperbridge.git", rev = "7adb936a6fdf4a9cc418259bf0cec35a31ce35d8" }
sync-committee-verifier = { git = "https://github.com/polytope-labs/hyperbridge.git", rev = "7adb936a6fdf4a9cc418259bf0cec35a31ce35d8" }
sync-committee-prover = { git = "https://github.com/polytope-labs/hyperbridge.git", rev = "7adb936a6fdf4a9cc418259bf0cec35a31ce35d8" }
trie-db = { version = "0.28.0" }

[features]
default = ["std"]
std = [
    "ibc/std",
    "ibc-proto/std",
    "prost/std",
    "prost-types/std",
    "anyhow/std",
    "serde/std",
    "sync-committee-verifier/std",
    "sync-committee-primitives/std",
    "ssz-rs/std",
    "tendermint/std",
    "trie-db/std",
    "rlp/std",
]
testnet = [
    "sync-committee-primitives/sepolia",
    "sync-committee-verifier/sepolia",
]
no_beacon = []