[package]
name = "light-client-common"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[features]
default = ["std"]
std = [
    "anyhow/std",
    "codec/std",
    "primitive-types/std",
    "ibc/std",
]

[dependencies]
# crates.io
anyhow = { version = "1.0.65", default-features = false }
codec = { version = "3.2.1", package = "parity-scale-codec", default-features = false }
primitive-types = { version = "0.11.1", default-features = false }
# ibc
ibc = { git = "https://github.com/ComposableFi/ibc-rs", rev = "a3b905f1429734bd3e1fc65ddb9d91aa40ee8250", default-features = false }
