version: "3.7"
services:
  relaychain-alice:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --beefy
      - --enable-offchain-indexing=true
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  relaychain-bob:
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --beefy
      - --enable-offchain-indexing=true
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  relaychain-charlie:
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - relaychain-charlie:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=charlie
      - --charlie
      - --rpc-methods=unsafe
      - --beefy
      - --enable-offchain-indexing=true
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  relaychain-dave:
    ports:
      - 9947:9944
      - 9936:9933
      - 30336:30333
    volumes:
      - relaychain-dave:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=dave
      - --dave
      - --rpc-methods=unsafe
      - --beefy
      - --enable-offchain-indexing=true
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  relaychain-eve:
    ports:
      - 9948:9944
      - 9937:9933
      - 30337:30333
    volumes:
      - relaychain-eve:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=eve
      - --eve
      - --rpc-methods=unsafe
      - --beefy
      - --enable-offchain-indexing=true
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  relaychain-ferdie:
    ports:
      - 9949:9944
      - 9938:9933
      - 30338:30333
    volumes:
      - relaychain-ferdie:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=ferdie
      - --ferdie
      - --rpc-methods=unsafe
      - --beefy
      - --enable-offchain-indexing=true
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  parachain-2000-0:
    ports:
      - 9188:9944
      - 9939:9933
      - 30339:30333
    volumes:
      - parachain-2000-0:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --no-mdns
      - --base-path=/data
      - --chain=/app/dev.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --alice
      - --bootnodes=/dns4/parachain-2000-0/tcp/30343/p2p/12D3KooWNDsLfXwYCiNSV3LWAwc3rJ7cdjqenzvzsvp1PTtCpbpo
      - --bootnodes=/dns4/parachain-2000-1/tcp/30344/p2p/12D3KooWAsyq4qfdTsuSfyka1qgwYHc9FjxFsfw3W1wrwzTJZnj1
      - --bootnodes=/dns4/parachain-2000-2/tcp/30345/p2p/12D3KooWSPz4uqbC2ywC671YxdKv5SozfnxCLeoobqYKDEP3zY4E
      - --node-key=7c667a99279cf5a884d6bb86fac6e320ef2d413dc880f01ff0e1ad353d615045
      - --port=30343
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --name=relaychain-alice
      - --enable-offchain-indexing=true
    environment: {}
    ulimits: *a1
  parachain-2000-1:
    ports:
      - 9951:9944
      - 9940:9933
      - 30340:30333
    volumes:
      - parachain-2000-1:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --no-mdns
      - --base-path=/data
      - --chain=/app/dev.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-1
      - --collator
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --bob
      - --bootnodes=/dns4/parachain-2000-0/tcp/30343/p2p/12D3KooWNDsLfXwYCiNSV3LWAwc3rJ7cdjqenzvzsvp1PTtCpbpo
      - --bootnodes=/dns4/parachain-2000-1/tcp/30344/p2p/12D3KooWAsyq4qfdTsuSfyka1qgwYHc9FjxFsfw3W1wrwzTJZnj1
      - --bootnodes=/dns4/parachain-2000-2/tcp/30345/p2p/12D3KooWSPz4uqbC2ywC671YxdKv5SozfnxCLeoobqYKDEP3zY4E
      - --node-key=24b3e641a85a3a85391bad7afc808afa526205ab01fd38774d9996a738d6082e
      - --port=30344
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --enable-offchain-indexing=true
    environment: {}
    ulimits: *a1
  parachain-2000-2:
    ports:
      - 9952:9944
      - 9941:9933
      - 30341:30333
    volumes:
      - parachain-2000-2:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --no-mdns
      - --base-path=/data
      - --chain=/app/dev.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-2
      - --collator
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --charlie
      - --bootnodes=/dns4/parachain-2000-0/tcp/30343/p2p/12D3KooWNDsLfXwYCiNSV3LWAwc3rJ7cdjqenzvzsvp1PTtCpbpo
      - --bootnodes=/dns4/parachain-2000-1/tcp/30344/p2p/12D3KooWAsyq4qfdTsuSfyka1qgwYHc9FjxFsfw3W1wrwzTJZnj1
      - --bootnodes=/dns4/parachain-2000-2/tcp/30345/p2p/12D3KooWSPz4uqbC2ywC671YxdKv5SozfnxCLeoobqYKDEP3zY4E
      - --node-key=1fde77550f57996e6c72a83d8a60bd3de50abc517f1b4bc51dcdafe71b22d4ec
      - --port=30345
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --enable-offchain-indexing=true
    environment: {}
    ulimits: *a1
  parachain-2001-0:
    ports:
      - 9988:9944
      - 9942:9933
      - 30342:30333
    volumes:
      - parachain-2001-0:/data
    build:
      context: .
      dockerfile: parachain-2001.Dockerfile
    command:
      - --no-mdns
      - --base-path=/data
      - --chain=/app/dev.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2001-0
      - --collator
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --alice
      - --bootnodes=/dns4/parachain-2001-0/tcp/30353/p2p/12D3KooWSMHyxxKbzzJxe44hHwSx7KWZM6Go3SrdhcvGLyc4z4XZ
      - --bootnodes=/dns4/parachain-2001-1/tcp/30354/p2p/12D3KooWBXGvCrjYujzbg9BnkqbiT6uKBTTT3HVAVKwQrgaAvGpV
      - --bootnodes=/dns4/parachain-2001-2/tcp/30355/p2p/12D3KooWKa7AwxfFtEXVVs6GsxGkp5gKfZ6FMQGuyji5rxNEgwB7
      - --node-key=e5ad8b579451f25035feeccaee89468a7fba53fbce35d27afe5fdbbf412722e9
      - --port=30353
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --enable-offchain-indexing=true
    environment: {}
    ulimits: *a1
  parachain-2001-1:
    ports:
      - 9954:9944
      - 9943:9933
      - 30343:30333
    volumes:
      - parachain-2001-1:/data
    build:
      context: .
      dockerfile: parachain-2001.Dockerfile
    command:
      - --no-mdns
      - --base-path=/data
      - --chain=/app/dev.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2001-1
      - --collator
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --bob
      - --bootnodes=/dns4/parachain-2001-0/tcp/30353/p2p/12D3KooWSMHyxxKbzzJxe44hHwSx7KWZM6Go3SrdhcvGLyc4z4XZ
      - --bootnodes=/dns4/parachain-2001-1/tcp/30354/p2p/12D3KooWBXGvCrjYujzbg9BnkqbiT6uKBTTT3HVAVKwQrgaAvGpV
      - --bootnodes=/dns4/parachain-2001-2/tcp/30355/p2p/12D3KooWKa7AwxfFtEXVVs6GsxGkp5gKfZ6FMQGuyji5rxNEgwB7
      - --node-key=83a1c624e290774605243c1517b79e992fd9de1cf43f7bdb5927a4c5b8e04d0c
      - --port=30354
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --enable-offchain-indexing=true
    environment: {}
    ulimits: *a1
  parachain-2001-2:
    ports:
      - 9955:9944
      - 9144:9933
      - 30344:30333
    volumes:
      - parachain-2001-2:/data
    build:
      context: .
      dockerfile: parachain-2001.Dockerfile
    command:
      - --no-mdns
      - --base-path=/data
      - --chain=/app/dev.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2001-2
      - --collator
      - --rpc-methods=unsafe
      - --wasmtime-instantiation-strategy=recreate-instance-copy-on-write
      - --log=ibc_transfer=trace,pallet_ibc=trace,grandpa-verifier=trace,runtime=trace
      - --force-authoring
      - --execution=wasm
      - --charlie
      - --bootnodes=/dns4/parachain-2001-0/tcp/30353/p2p/12D3KooWSMHyxxKbzzJxe44hHwSx7KWZM6Go3SrdhcvGLyc4z4XZ
      - --bootnodes=/dns4/parachain-2001-1/tcp/30354/p2p/12D3KooWBXGvCrjYujzbg9BnkqbiT6uKBTTT3HVAVKwQrgaAvGpV
      - --bootnodes=/dns4/parachain-2001-2/tcp/30355/p2p/12D3KooWKa7AwxfFtEXVVs6GsxGkp5gKfZ6FMQGuyji5rxNEgwB7
      - --node-key=4e658718a1f0f8950b16f31eb143ed238f6e93d51507e5bcfa9376690576b1fd
      - --port=30355
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --enable-offchain-indexing=true
    environment: {}
    ulimits: *a1
  # netshoot: # sidecar container for debug purposes
  #   image: nicolaka/netshoot
  #   command: |
  #     sleep 365d
volumes:
  relaychain-alice: null
  relaychain-bob: null
  relaychain-charlie: null
  relaychain-dave: null
  relaychain-eve: null
  relaychain-ferdie: null
  parachain-2000-0: null
  parachain-2000-1: null
  parachain-2000-2: null
  parachain-2001-0: null
  parachain-2001-1: null
  parachain-2001-2: null