[package]
name = "ibc-rpc"
description = "RPC apis for substrate ibc"
edition = "2021"
version = "0.1.0"
authors = ["David Salami <wizdave97@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true }
ibc-primitives = { path = "../primitives" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
pallet-ibc = { path = ".." }
serde = { workspace = true }
serde_json = "1.0.45"

frame-system = { workspace = true }
ibc-proto = { path = "../../../ibc/proto", default-features = false }
ibc-runtime-api = { path = "../runtime-api" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-trie = { workspace = true }
tendermint-proto = { workspace = true }

[dependencies.ibc]
path = "../../../ibc/modules"
default-features = false

[dependencies.ibc-derive]
path = "../../../ibc/derive"
default-features = false
