type = "cosmos"
name = "centauri_mainnet"
rpc_url = "https://rpc-composable-ia.cosmosia.notional.ventures"
grpc_url = "https://grpc-composable-ia.cosmosia.notional.ventures"
websocket_url = "ws://rpc-composable-ia.cosmosia.notional.ventures/websocket"
chain_id = "centauri-1"
client_id = "07-tendermint-30"
connection_id = "connection-2"
account_prefix = "centauri"
fee_denom = "ppica"
fee_amount = "1500000"
gas_limit = 10000000000
store_prefix = "ibc"
max_tx_size = 20000000
wasm_code_id = "58c7623a3ab78f4cb2e4c5d02876ac36c3b38bb472118173a7ec7faa688a66d2"
channel_whitelist = [["channel-1", "transfer"]]
mnemonic = "bottom loan skill merry east cradle onion journey palm apology verb edit desert impose absurd oil bubble sweet glove shallow size build burst effort"
skip_optional_client_updates = false