type = "cosmos"
name = "centauri"
rpc_url = "http://127.0.0.1:26657/"
grpc_url = "http://127.0.0.1:9090/"
websocket_url = "ws://127.0.0.1:26657/websocket"
chain_id = "centauri-testnet-1"
client_id = "07-tendermint-9"
connection_id = "connection-3"
account_prefix = "centauri"
fee_denom = "pica"
fee_amount = "4000"
gas_limit = 9223372036854775806
store_prefix = "ibc"
max_tx_size = 200000
wasm_code_id = "7124c9cb0eb7eafe336e92652d24b0ce8204bfff49962727cf18cbcb94fb87bd"
channel_whitelist = [["channel-0", "transfer"]]
mnemonic = "sense state fringe stool behind explain area quit ugly affair develop thumb clinic weasel choice atom gesture spare sea renew penalty second upon peace"
skip_optional_client_updates = true
max_packets_to_process = 200
