type = "cosmos"
name = "centauri"
rpc_url = "http://10.132.0.6:26657/"
grpc_url = "http://10.132.0.6:9999/"
websocket_url = "ws://10.132.0.6:26657/websocket"
chain_id = "centauri-1"
client_id = "07-tendermint-2"
connection_id = "connection-96"
account_prefix = "centauri"
fee_denom = "ppica"
fee_amount = "200000"
gas_limit = 100000000
store_prefix = "ibc"
max_tx_size = 200000
wasm_code_id = "66ce7420d21e2555b0e6ce952c0826590fb5f6508a9ac84a5c11178cec58a303"
channel_whitelist = [["channel-61", "transfer"]]
mnemonic = "scissors enroll comfort wrist eight catch decide stage squirrel phrase close december staff baby stable mirror hand allow sort dish wrist gas quantum puppy"
skip_optional_client_updates = true
max_packets_to_process = 50