http_rpc_url = "http://localhost:8545/"
ws_rpc_url = "ws://localhost:8545/"
beacon_rpc_url = "http://localhost:3500/"
private_key = "-----BEGIN EC PRIVATE KEY-----\rMGsCAQEEIKwJdL7Dmhfja6SmtNI4/5RLrLR4y+1e/K54TXv08v+AoUQDQgAEgxhT\rW1QQXUp6rmDAj8RflocYG0/fxiW9GnU/pzl/7XU1R/EcqGlmRvLzrLCOMQFq+sI+\rYwxdEfWfYf71ew0qpQ==\r-----END EC PRIVATE KEY-----\r"
max_block_weight = 1
name = "ethereum-client"
client_id = "07-tendermint-0"
channel_whitelist = []
commitment_prefix = "696263"
diamond_address = "0xb7f8bc63bbcad18155201308c8f3540b07f84f5e"
tendermint_address = "0x0b306bf915c4d645ff596e518faf3f9669b97016"
gov_proxy_address = "0xa51c1fc2f0d1a1b8494ed1fe312d7c3a78ed91c0"
ics20_transfer_bank_address = "0x68b1d87f95878fe05b998f19b66f4baba5de1aed"
ics20_bank_address = "0x9a9f2ccfde556a7e9ff0848998aa4a0cfd8863ae"
diamond_facets = [
    [
    "IBCClient",
    "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
],
    [
    "IBCConnection",
    "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
],
    [
    "IBCChannelHandshake",
    "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
],
    [
    "IBCPacket",
    "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
],
    [
    "IBCQuerier",
    "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
],
    [
    "DiamondCutFacet",
    "0x0165878a594ca255338adfa4d48449f69242eb8f",
],
    [
    "DiamondLoupeFacet",
    "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
],
    [
    "OwnershipFacet",
    "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
],
    [
    "GovernanceFacet",
    "0x8a791620dd6260079bf849dc5567adc3f2fdc318",
],
    [
    "RelayerWhitelistFacet",
    "0x610178da211fef7d417bc0e6fed39f05609ad788",
],
]
client_type = "07-tendermint"
indexer_pg_url = "pg://postgres:password@localhost/postgres"
indexer_redis_url = "redis://localhost:6379"
skip_optional_client_updates = true
max_packets_to_process = 50
client_update_interval_sec = 10
