http_rpc_url = "http://localhost:8545/"
ws_rpc_url = "ws://127.0.0.1:8546/"
beacon_rpc_url = "http://localhost:3500/"
private_key_path = "/Users/vmark/work/centauri-private/hyperspace/ethereum/keys/0x73db010c3275eb7a92e5c38770316248f4c644ee"
max_block_weight = 1
name = "ethereum-client"
client_id = "07-tendermint-0"
channel_whitelist = []
commitment_prefix = "696263"
ibc_core_diamond_address = "0x56378f9b88f341b1913a2fc6ac2bcbaa1b9a9f9f"
ibc_core_facets = [
    [
        "DiamondCutFacet",
        "0xb7198a3674e37433579be45aa9dd09f5ab4b314a",
    ],
    [
        "DiamondLoupeFacet",
        "0xb26397cfa7e111e844086bdd3da5080f9de65cb7",
    ],
    [
        "OwnershipFacet",
        "0xfbf766071d0fdee42b78ab029b97194543b6d7a5",
    ],
    [
        "CallBatchFacet",
        "0x844d2447e6c00cf6a5fbe9ad5eebebe31e40368e",
    ],
    [
        "IBCClient",
        "0x992966599e81b9d4a3ef92172b9fa162d2e50d5b",
    ],
    [
        "IBCConnection",
        "0x3bf46cf159422e1791d20d45683b21f34ecae4be",
    ],
    [
        "IBCChannelHandshake",
        "0xb16af4cfc553ae0a8f43e812e22dc6caabdf5e63",
    ],
    [
        "IBCPacket",
        "0x4f6e145fbaf72be9ea283f5793e70a1c594d5ceb",
    ],
    [
        "IBCQuerier",
        "0xd0017ae5068faa14eaa547ba1c47fdc7afdf1230",
    ],
    [
        "RelayerWhitelistFacet",
        "0xe566a7e344f2aef783319a76233e54e7f8b47823",
    ],
]
tendermint_diamond_address = "0xd6085b6c6503b0fc994fdbdd4b780a6e819e882a"
tendermint_facets = [
    [
        "DiamondCutFacet",
        "0xb7198a3674e37433579be45aa9dd09f5ab4b314a",
    ],
    [
        "DiamondLoupeFacet",
        "0xb26397cfa7e111e844086bdd3da5080f9de65cb7",
    ],
    [
        "OwnershipFacet",
        "0xfbf766071d0fdee42b78ab029b97194543b6d7a5",
    ],
    [
        "TendermintLightClientZK",
        "0x4976bb932815783f092dd0e3cca567d5502be46e",
    ],
]
ibc_transfer_diamond_address = "0x481796b2a6cf91a68e18b42dedc98c035734043f"
ibc_transfer_facets = [
    [
        "ICS20TransferBank",
        "0xcf4210c1f5e1558f58300fea9b8398ab74f8900a",
    ],
    [
        "DiamondCutFacet",
        "0xb7198a3674e37433579be45aa9dd09f5ab4b314a",
    ],
    [
        "DiamondLoupeFacet",
        "0xb26397cfa7e111e844086bdd3da5080f9de65cb7",
    ],
    [
        "OwnershipFacet",
        "0xfbf766071d0fdee42b78ab029b97194543b6d7a5",
    ],
]
bank_diamond_address = "0xbc9098af79b4a35defef8a16098b94454849a540"
bank_facets = [
    [
        "ICS20Bank",
        "0x40ec3b1c0dc9332fe3202328a11b4805331e2b3a",
    ],
    [
        "DiamondCutFacet",
        "0xb7198a3674e37433579be45aa9dd09f5ab4b314a",
    ],
    [
        "DiamondLoupeFacet",
        "0xb26397cfa7e111e844086bdd3da5080f9de65cb7",
    ],
    [
        "OwnershipFacet",
        "0xfbf766071d0fdee42b78ab029b97194543b6d7a5",
    ],
]
gov_proxy_address = "0xd82c3e06ba4a201680f27d0f0530fe00718a109f"
client_type = "07-tendermint"
jwt_secret_path = "/Users/vmark/work/eth-pos-devnet/execution/jwtsecret"
indexer_pg_url = "pg://postgres:password@localhost/postgres"
indexer_redis_url = "redis://localhost:6379"
skip_optional_client_updates = true
max_packets_to_process = 50
client_update_interval_sec = 10
