type = "solana"
name = "solana"
rpc_url = "https://mainnet.helius-rpc.com/?api-key=cdaa6aa6-237b-4eef-8788-6c0690093d19"
ws_url = "wss://mainnet.helius-rpc.com/?api-key=cdaa6aa6-237b-4eef-8788-6c0690093d19"
chain_id = "solana-1"
client_id = "08-wasm-0"
connection_id = "connection-26"
account_prefix = "ibc"
fee_denom = "stake"
fee_amount = "4000"
gas_limit = 100000000
store_prefix = "ibc"
max_tx_size = 320000
commitment_prefix = [105, 98, 99]
channel_whitelist = [["channel-4", "transfer"]]
commitment_level = "confirmed"
private_key = [16, 107, 33, 155, 71, 242, 73, 170, 98, 1, 110, 164, 13, 159, 16, 31, 121, 24, 10, 198, 123, 138, 192, 32, 134, 128, 72, 108, 10, 167, 111, 28, 147, 24, 213, 27, 143, 49, 73, 167, 196, 210, 110, 83, 197, 174, 50, 161, 160, 111, 245, 72, 122, 108, 160, 56, 157, 134, 186, 86, 232, 184, 8, 176]
solana_ibc_program_id = "FeFjYj2YuMsk87Cp48ubzQPtW4MWDaKJrCs1TcdgosZJ"
write_program_id = "FufGpHqMQgGVjtMH9AV8YMrJYq8zaK6USRsJkZP4yDjo"
signature_verifier_program_id = "C6r1VEbn3mSpecgrZ7NdBvWUtYVJWrDPv4uU9Xs956gc"

[common_state_config]
skip_optional_client_updates = true
max_packets_to_process = 10
client_update_interval_sec = 0
handshake_completed = false
