type = "solana"
name = "solana"
client_id = "08-wasm-153"
# connection_id = "connection-19"
commitment_prefix =[105, 98, 99]
rpc_url ="https://devnet.helius-rpc.com/?api-key=bc5c0cfc-46df-4781-978f-af6ca7a202c2"
ws_url ="wss://devnet.helius-rpc.com/?api-key=bc5c0cfc-46df-4781-978f-af6ca7a202c2"
chain_id ="solana-1"
account_prefix ="ibc"
fee_denom ="stake"
fee_amount ="4000"
gas_limit =100000000
store_prefix ="ibc"
max_tx_size =320000
channel_whitelist =[]
commitment_level ="confirmed"
private_key =[
	48, 123, 8, 80, 248, 0, 217, 142, 124, 193, 95, 24, 168, 139, 214, 136, 147, 210, 168,
	135, 26, 36, 162, 89, 150, 185, 99, 191, 247, 135, 78, 111, 12, 8, 4, 81, 129, 165,
	153, 230, 192, 225, 51, 119, 216, 14, 69, 225, 73, 7, 204, 144, 39, 213, 91, 255, 136,
	38, 95, 131, 197, 4, 101, 186,
]
solana_ibc_program_id ="9FeHRJLHJSEw4dYZrABHWTRKruFjxDmkLtPmhM5WFYL7"
write_program_id ="FufGpHqMQgGVjtMH9AV8YMrJYq8zaK6USRsJkZP4yDjo"
signature_verifier_program_id ="C6r1VEbn3mSpecgrZ7NdBvWUtYVJWrDPv4uU9Xs956gc"

[common_state_config]
skip_optional_client_updates =true
max_packets_to_process =10
