[package]
name = "ics08-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version = "0.11", default-features = false }
ibc = { path = "../../ibc/modules", default-features = false }
ibc-proto = { path = "../../ibc/proto", default-features = false }