[package]
name = "ics08-wasm"
version = "0.15.0"
edition = "2021"

[dependencies]
prost = { version = "0.11", default-features = false }
ibc = { path = "../../ibc/modules", default-features = false }
ibc-proto = { path = "../../ibc/proto", default-features = false }
spin = { version = "0.9.4", default-features = false, features = ["rwlock"] }
hex = { version = "0.4.3", default-features = false }
cosmwasm-schema = { version = "1.1.3", default-features = false, optional = true }
serde = { version = "1.0.145", default-features = false, features = ["derive"], optional = true }

[features]
default = []
std = ["ibc/std", "ibc-proto/std", "prost/std", "hex/std", "spin/std" ]
cosmwasm = ["cosmwasm-schema", "std", "serde", "ibc/cosmwasm"]