[package]
name = "cf-guest-cw"
version = "0.0.0"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.6
"""

[dependencies]
base64 = "0.22"
borsh = { version = "0.10.3", default-features = false }
cf-guest = { path = "../../../emulated-light-client/common/cf-guest", default-features = false }
guestchain = { path = "../../../emulated-light-client/common/guestchain", default-features = false }

cosmwasm-schema = "1.5.3"
cosmwasm-std = "1.5.3"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
sha2 = "0.10"
sha3 = "0.10"
derive_more = "0.99.17"

ed25519 = { version = "1.5", default-features = false }
ed25519-consensus = { version = "2", optional = true, default-features = false }
ibc = { version = "0.50", default-features = false, features = ["serde", "schema"] }
#ibc-derive = { version = "0.50", default-features = false }
#ibc-proto = { version = "0.41", default-features = false }
ics23 = { git = "https://github.com/cosmos/ics23", rev = "74ce807b7be39a7e0afb4e2efb8e28a57965f57b", default-features = false }
prost = { version = "0.12.3", default-features = false }
ed25519-zebra = { version = "3.1.0", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
digest = { version = "0.10.3", default-features = false }
hex = "0.4.3"

[dev-dependencies]
cw-multi-test = "0.15.1"
hex = "0.4.3"
hyperspace-primitives = { path = "../../hyperspace/primitives", features = ["testing"] }
pallet-ibc = { path = "../../contracts/pallet-ibc" }
serde-json-wasm = { version = "0.5.0", default-features = false }
serde_json = { version = "1.0.93", default-features = false }

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []
default = ["rust-crypto"]
rust-crypto = ["ed25519-consensus"]
std = [
	"byteorder/std",
	"digest/std",
	"ed25519/std",
	"ed25519-consensus?/std",
	"ed25519-zebra/std",
	"hex/std",
	"ibc/std",
	"ics23/std",
	"pallet-ibc/std",
	"prost/std",
	"serde/std",
	"serde_json/std",
	"sha2/std",
	"sha3/std",
]
test = [
  "std"
]
