[package]
name = "simnode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-simnode = { git = "https://github.com/polytope-labs/sc-simnode", rev = "a7f6c574398a7fe8d48b5b8177e68426d70b2ba5" }
parachain-runtime = { path = "../parachain-node/runtime" }
parachain-node = { path = "../parachain-node" }
jsonrpsee = { workspace = true, features = ["server"] }
frame-system = { workspace = true }
pallet-sudo = { workspace = true }
sp-transaction-pool = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sc-cli = { workspace = true, default-features = false }
sc-client-api = { workspace = true, default-features = false }
sc-executor = { workspace = true, default-features = false }
sc-consensus = { workspace = true, default-features = false }
sc-consensus-manual-seal = { workspace = true, default-features = false }
sc-service = { workspace = true, default-features = false }
sp-runtime = { workspace = true }
sp-consensus-aura = { workspace = true, default-features = false }

pallet-transaction-payment = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false }
cumulus-primitives-parachain-inherent = { workspace = true }
light-client-common = { workspace = true }
pallet-ibc = { workspace = true, features = [ "runtime-benchmarks" ] }
ibc = { workspace = true }
ics10-grandpa = { workspace = true }
grandpa-light-client-primitives = { workspace = true }