[package]
name = "hyperspace-cosmos"
version = "0.1.0"
edition = "2021"
authors = ["Composable Developers"]

[dependencies]
primitives = { path = "../primitives", package = "hyperspace-primitives" }

# crates.io
anyhow = "1.0.65"
futures = "0.3.21"
async-trait = "0.1.53"
log = "0.4.17"
env_logger = "0.9.0"
hex = "0.4.3"
tokio = { version = "1.19.2", features = ["macros", "sync"] }
rs_merkle = "1.2.0"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex-literal = "0.3.4"
serde_json = "1.0.74"
derive_more = { version = "0.99", features = ["from"]  }
serde = {version="1.0.137", features = ["derive"]}
tokio-stream = { version = "0.1.9", features = ["sync"]}
thiserror = "1.0.31"
itertools = "0.10.3"
jsonrpsee = "0.15.1"
jsonrpsee-ws-client = "0.14.0"
prost = { version = "0.11" }
k256 = { version = "0.11.6", features = ["ecdsa-core", "ecdsa", "sha256"] }

# composable
ibc = { path = "../../ibc/modules", features = [] }
ibc-proto = { path = "../../ibc/proto" }
#tendermint-proto = { git = "https://github.com/composableFi/tendermint-rs", rev = "2c513dcaf2385d5b5f55e129a5ed11cc8d8ad5d0", default-features = false }
#light-client-common = { path = "../../light-clients/common" }
ibc-relayer-types = { git = "https://github.com/informalsystems/hermes.git" }

# tendermint
tendermint = { version = "0.27.0", default-features = false, features = [
    "secp256k1",
] }
tendermint-proto = { version = "0.27.0", default-features = false }
tendermint-rpc = { version = "0.27.0", features = [
    "http-client",
    "websocket-client",
] }
tendermint-light-client = { version = "0.27.0", default-features = false, features = [
    "rpc-client",
    "secp256k1",
    "unstable",
] }
tendermint-light-client-verifier = { version = "0.27.0", default-features = false }
# tendermint-testgen = { version = "0.25.0" }
