[package]
name = "hyperspace-cosmos"
version = "0.1.0"
edition = "2021"
authors = ["Farhad Shabani <farhad.shabani@gmail.com>"]

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.53"
bech32 = "0.9.1"
bitcoin = { version = "0.29.1", features = ["serde"] }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
dirs-next = "2.0.0"
log = "0.4.17"
env_logger = "0.9.0"
futures = "0.3.21"
primitives = { path = "../primitives", package = "hyperspace-primitives" }
jsonrpsee = "0.15.1"
jsonrpsee-ws-client = "0.14.0"
serde = {version="1.0.137", features = ["derive"]}
serde_json = { version = "1" }
ss58-registry = "1.28.0"
thiserror = "1.0.31"
tonic = { version = "0.7.2", features = ["tls", "tls-roots"] }

# ibc
ibc = { path = "../../ibc/modules", features = [] }
ibc-proto = { path = "../../ibc/proto" }
ibc-rpc = { path = "../../contracts/pallet-ibc/rpc" }
pallet-ibc = { path = "../../contracts/pallet-ibc" }
# light-client-common = { path = "../../light-clients/common" }


# Tendermint
tendermint = { git = "https://github.com/farhad-shabani/tendermint-rs", rev= "ab7db0fa89e1634ad9855bc567ba02d9e8916426", default-features = false }
tendermint-rpc   = { git = "https://github.com/farhad-shabani/tendermint-rs", rev= "ab7db0fa89e1634ad9855bc567ba02d9e8916426", features = ["http-client", "websocket-client"] }
tendermint-proto = { git = "https://github.com/farhad-shabani/tendermint-rs", rev= "ab7db0fa89e1634ad9855bc567ba02d9e8916426" }
ics07-tendermint = { path = "../../light-clients/ics07-tendermint" }
tendermint-light-client = { git = "https://github.com/farhad-shabani/tendermint-rs", rev= "ab7db0fa89e1634ad9855bc567ba02d9e8916426", default-features = false, features = ["rpc-client", "secp256k1", "unstable"] }
tendermint-light-client-verifier = { git = "https://github.com/farhad-shabani/tendermint-rs", rev= "ab7db0fa89e1634ad9855bc567ba02d9e8916426", default-features = false }
tendermint-prover = { path = "../../algorithms/tendermint/prover" }
tendermint-verifier = { path = "../../algorithms/tendermint/verifier" }
tendermint-primitives = {  path = "../../algorithms/tendermint/primitives" }

# Substrate
subxt = { git = "https://github.com/paritytech/subxt", rev = "51179a8b72472d0b43c91cda75a1ddc3fddb9555" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", features = ["full_crypto"] }

[features]
testing = ["primitives/testing"]