[package]
name = "compress"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = { version = "0.12.2", default-features = false }

[dev-dependencies]
hex = { version = "0.4.3", default-features = false }

[features]
std = [
    "primitive-types/std"
]
default = ["std"]