[package]
name = "hyperspace-ethereum"
version = "0.1.0"
edition = "2021"
authors = ["Composable Developers"]

[dependencies]
primitives = { path = "../primitives", package = "hyperspace-primitives" }

# composable
ibc = { path = "../../ibc/modules", features = [] }
ibc-proto = { path = "../../ibc/proto" }
ibc-primitives = { path = "../../contracts/pallet-ibc/primitives" }
ics07-tendermint = { path = "../../light-clients/ics07-tendermint" }
ibc-rpc = { path = "../../contracts/pallet-ibc/rpc" }
pallet-ibc = { path = "../../contracts/pallet-ibc" }

ethers = "2.0.3"
tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.28"
anyhow = "1.0.65"
